version: "3.8"
services:

  postgres:
    image: postgres:13
    ports:
      - "5440:5432"
    volumes:
      - ../utils/strapi_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cms-strapi

volumes:
  node_modules:
